# Generated by Django 5.0.3 on 2024-03-19 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_alter_articlecategory_options_alter_articles_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['-createdOn']},
        ),
    ]
