# Generated by Django 5.0.2 on 2024-03-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_alter_articles_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
