# Generated by Django 5.0.2 on 2024-05-08 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_author_article_headerimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
