# Generated by Django 5.0.2 on 2024-03-20 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0002_alter_product_producttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-name']},
        ),
    ]
