# Generated by Django 5.0.2 on 2024-03-20 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
