# Generated by Django 5.0.4 on 2024-05-05 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_alter_job_status_alter_jobapplication_status'),
        ('user_management', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.profile'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('1', 'Open'), ('2', 'Full')], default='1', max_length=25),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Accepted'), ('3', 'Rejected')], default='1', max_length=25),
        ),
    ]
